""" Game how is ask a question and a joke to answer."""

print('What is be, that you defecate on the table?')
input()
print('The great deal.')
print()
print('What bitches ask a \'black whole\'?')
input()
print('Kariosus!')
print()
print('Knock-knock.')
input()
print("Where is that?")
input()
print('Dumb bitch.')
input()
print('Dumb bitch?', end='')
print('-MOOOO!')
